server:
    port: 9000
    contextPath:

spring:
    profiles:
        active: dev


    dataSource:
      driverClassName: org.hibernate.dialect.MySQL5InnoDBDialect
      url: jdbc:mysql://localhost/yiding?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: 741369

    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hbm2ddl.auto: update
      show_sql: true

    freemarker:
      template-loader-path: classpath:/view/
      suffix: .html
      content-type: text/html
      charset: utf-8
      cache: false
      template_update_delay: 0
      prefer-file-system-access: true
      check-template-location: false
      request-context-attribute: request
      expose-request-attributes: true
      expose-session-attributes: true

    http:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400
    

